spring:
  datasource:
    url:
    username:
    password:
    driverClassName: org.postgresql.Driver
  main:
    banner-mode: off


bot:
  username:
  token:
  chatId:
  urlMessage: https://api.telegram.org/bot${bot.token}/sendMessage
  urlPhoto: https://api.telegram.org/bot${bot.token}/sendPhoto

chatId:

api:
  football:
    token:

season: 2024

logging:
  level:
    org:
      springframework:
        security: DEBUG
